version: "3.8"

services:
  vulnlab:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock       # Mount Docker socket
      - /:/host_root                                    # Mount full host root fs (optional)
    privileged: true 