version: '3.8'

services:
  app:
    build: .
    container_name: vuln-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: vuln-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - /var/run/docker.sock:/var/run/docker.sock       # Mount Docker socket
      - /:/host_root   

volumes:
  mongo-data:

